package sundial;

/**
 * Any author is welcomed to put their name here ^^
 * 
 * @author briceorbryce
 */
public class AboutPage extends javax.swing.JDialog {

	/**SerialVersionUID*/
	private static final long serialVersionUID = 1L;
	
	
	/**
	 * Creates new form AboutPage
	 * 
	 * @param parent is SunDialFrame
	 * @param modal is unknown (because it was gen by Netbeans
	 */
	public AboutPage(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		
		// Sets the location to the middle of the screen
		setLocationRelativeTo(null);
	}

	/**
	 * This is message is automatically generated by netbeans
	 * 
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {

		this.jLabel1 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		addMouseListener(new java.awt.event.MouseAdapter() {
			@Override
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				closeWindow(evt);
			}
		});

		this.jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N //$NON-NLS-1$
		this.jLabel1.setText("About"); //$NON-NLS-1$

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGap(153, 153, 153)
						.addComponent(this.jLabel1)
						.addContainerGap(176, Short.MAX_VALUE))
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(this.jLabel1)
						.addContainerGap(260, Short.MAX_VALUE))
				);

		pack();
	}

	/**
	 * @param evt when the user clicks any part of the JDialog
	 */
	public void closeWindow(java.awt.event.MouseEvent evt) {
		
		// Closes the window when user clicks on it
		this.dispose();
	}
	
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel jLabel1;
	// End of variables declaration//GEN-END:variables
}
